targets:
  $default:
    sources:
      - lib/**
      - schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: lib/gql/fragment.graphql
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/gql/queries/*.graphql
              output: lib/gql/generated/generated.dart